import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.List;

public class Admin extends User{
  private String department;

  public Admin(String userId, String name, String email, String password, String department){
    super(userId, name, email, password, "Admin");
    this.department = department;
  }

  public String getDepartment() {
    return department;
  }

  public void setDepartment(String department) {
    this.department = department;
  }

  public void generateUserReport(List<User> users){
    System.out.println("===User Report===");
    System.out.println("Generated By: " + name + " on " + new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date()));
    System.out.println("Total Users: " + users.size());

    int students = 0, tutors = 0, admins = 0;
      for (User user : users) {
          if (user instanceof Student) students++;
          else if (user instanceof Tutor) tutors++;
          else if (user instanceof Admin) admins++;
      }
      
      System.out.println("Students: " + students);
      System.out.println("Tutors: " + tutors);
      System.out.println("Admins: " + admins);
      System.out.println("==================");
  }

  public void generateSessionReport(List<Session> sessions){
    System.out.println("===SESSION REPORT===");
    System.out.println("Generated By: " + name + " on " +  new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date()));
    System.out.println("Total Sessions: " + sessions.size());

    int totalParticipants = 0;
        for (Session session : sessions) {
            totalParticipants += session.getParticipants().size();
        }
        
        System.out.println("Total Enrollments: " + totalParticipants);
        if (sessions.size() > 0) {
            System.out.println("Average Participants per Session: " + (totalParticipants / sessions.size()));
        }
        System.out.println("=====================");
  }

  @Override
    public void displayProfile() {
        System.out.println("Admin Profile:");
        System.out.println(toString());
        System.out.println("Department: " + department);
    }
}
